import type { Character } from "../../domain/types";
import { getRestMoves, requiresRestRoll, restMoveDescription, restMoveLabels, type RestKind, type RestMoveChoice } from "./restRules";

export type RestRenderDependencies = { escapeHtml: (value: string) => string };
export function renderRestModal(character: Character | undefined, kind: RestKind | undefined, choices: RestMoveChoice[], error: string | undefined, deps: RestRenderDependencies): string {
  if (!character || !kind) return "";
  const selected = choices.length;
  const options = getRestMoves(kind).map((move) => { const count = choices.filter((choice) => choice.id === move).length; return `<button type="button" class="rest-move-option ${count ? "is-selected" : ""}" data-action="choose-rest-move" data-rest-move="${move}" ${selected >= 2 && !count ? "disabled" : ""}><strong>${restMoveLabels[move]}</strong><span>${restMoveDescription(kind, move)}</span>${count ? `<small>${count} ${count === 1 ? "escolha" : "escolhas"}</small>` : ""}</button>`; }).join("");
  const selectedMoves = choices.map((choice, index) => `<article class="rest-choice"><div><strong>${index + 1}. ${restMoveLabels[choice.id]}</strong><span>${requiresRestRoll(kind, choice.id) ? `Resultado: ${choice.roll ? choice.roll : "a definir"}` : restMoveDescription(kind, choice.id)}</span></div>${requiresRestRoll(kind, choice.id) ? `<div class="rest-roll-controls"><button type="button" data-action="roll-rest-d4" data-rest-choice-index="${index}">Rolar d4</button><label><span>Resultado</span><input data-rest-roll-index="${index}" type="number" min="1" max="4" value="${choice.roll ?? ""}" /></label></div>` : ""}<button type="button" class="icon-action" data-action="remove-rest-move" data-rest-choice-index="${index}" aria-label="Remover escolha">×</button></article>`).join("");
  return `<div class="modal-backdrop" data-modal-backdrop><section class="rest-modal" role="dialog" aria-modal="true" aria-labelledby="rest-modal-title"><button class="modal-close" type="button" data-modal-close aria-label="Fechar downtime">×</button><div class="rest-modal-heading"><h2 id="rest-modal-title">Downtime</h2></div><div class="rest-kind-switch"><button type="button" data-action="set-rest-kind" data-rest-kind="short" class="${kind === "short" ? "is-active" : ""}">Breve</button><button type="button" data-action="set-rest-kind" data-rest-kind="long" class="${kind === "long" ? "is-active" : ""}">Longo</button></div><p class="rest-guidance">${kind === "short" ? "Escolha dois movimentos. Os movimentos de recuperação usam 1d4 + Tier." : "Escolha dois movimentos. Recuperações de PV, Estresse e Armadura são completas."}</p><div class="rest-move-options">${options}</div><section class="rest-selections"><div class="section-heading"><h3>Movimentos escolhidos</h3><span>${selected}/2</span></div>${selectedMoves || "<p>Escolha até dois movimentos de downtime.</p>"}</section>${error ? `<p class="form-error">${deps.escapeHtml(error)}</p>` : ""}<div class="modal-actions"><button class="secondary-action" type="button" data-modal-close>Cancelar</button><button class="primary-action" type="button" data-action="confirm-rest" ${selected !== 2 ? "disabled" : ""}>Concluir descanso</button></div></section></div>`;
}
