import type { Attribute, ClassDefinition, CommunityDefinition, FeatureDefinition, SubclassDefinition } from "../../domain/types";
import { getClassDisplayName } from "../compendium/classPresentation";
import { characterCreationAttributes, formatCreationAttributeValue, getRemainingCreationAttributeValues } from "./attributeAllocation";

type EscapeHtml = (value: string) => string;

export function renderCreationIdentityStep(state: { name: string; community: string; portraitImage?: string }, escapeHtml: EscapeHtml): string {
  return `<div class="form-grid character-creation-identity creation-step-panel" data-creation-panel="1"><label class="form-field"><span>Nome</span><input data-character-name required maxlength="60" value="${escapeHtml(state.name)}" placeholder="Nome do personagem" /></label><label class="form-field form-field-wide"><span>Origem narrativa <small>(opcional)</small></span><input data-character-community maxlength="80" value="${escapeHtml(state.community)}" placeholder="Ex.: Vigília de Tristelo" /><small>Um local, grupo ou história particular do personagem. A comunidade mecânica será escolhida em uma etapa própria.</small></label><label class="form-field form-field-wide character-portrait-upload"><span>Foto do personagem</span><input data-character-portrait type="file" accept="image/png,image/jpeg,image/webp" /><small>${state.portraitImage ? "Foto selecionada. Você pode escolher outra para substituí-la." : "Opcional. PNG, JPG ou WebP; até 1,5 MB."}</small>${state.portraitImage ? `<img src="${escapeHtml(state.portraitImage)}" alt="Prévia do retrato" />` : ""}</label></div>`;
}

export function renderCreationExperiencesStep(experiences: Array<{ name: string }>, escapeHtml: EscapeHtml): string {
  return `<section class="character-creation-experiences creation-step-panel" data-creation-panel="8"><div><span>História</span><h3>Defina duas Experiências</h3><p>Cada uma começa em +2. Escolha frases específicas que expressem vivências, aptidões ou traços do personagem.</p></div><div class="form-grid">${experiences.map((experience, index) => `<label class="form-field form-field-wide"><span>Experiência ${index + 1} · +2</span><input data-character-experience-name="${index}" maxlength="80" value="${escapeHtml(experience.name)}" placeholder="Ex.: Vigia de fronteira" /><small>Evite termos muito amplos ou que concedam um poder específico.</small></label>`).join("")}</div></section>`;
}

export function renderCreationAttributesStep(values: Record<Attribute["id"], number>, selectedValue?: number, spellcastAttributeId?: Attribute["id"]): string {
  const available = getRemainingCreationAttributeValues(values);
  return `<section class="character-attributes-picker creation-step-panel" data-creation-panel="6"><div><span>Traços</span><p>Distribua seus atributos. Escolha uma pedra e encaixe-a no atributo desejado.</p><div class="character-attribute-available" aria-live="polite"><div><strong>Pedras disponíveis</strong></div><div class="character-attribute-token-list">${available.length ? available.map((value, index) => `<button type="button" class="character-attribute-token ${selectedValue === value && available.indexOf(value) === index ? "is-selected" : ""}" data-character-attribute-allocation="select" data-character-attribute-value="${value}" aria-pressed="${selectedValue === value && available.indexOf(value) === index}"><strong>${formatCreationAttributeValue(value)}</strong></button>`).join("") : "<span class=\"character-attribute-complete\">Todos encaixados</span>"}</div><button type="button" class="character-attribute-reset" data-character-attribute-allocation="reset">Resetar</button></div></div><div class="character-attribute-choice-grid">${characterCreationAttributes.map((attribute) => { const value = values[attribute.id]; const assigned = Number.isInteger(value); const isSpellcast = attribute.id === spellcastAttributeId; return `<button type="button" class="character-attribute-card ${assigned ? "is-assigned" : ""} ${selectedValue !== undefined ? "is-targetable" : ""} ${isSpellcast ? "is-spellcast" : ""}" data-character-attribute-allocation="assign" data-character-attribute-id="${attribute.id}"><span>${attribute.label}${isSpellcast ? '<em class="character-attribute-spellcast" title="Atributo de Conjuração">🪄 Conjuração</em>' : ""}</span><i class="character-attribute-slot" aria-hidden="true"><strong>${assigned ? formatCreationAttributeValue(value) : "—"}</strong></i><small>${attribute.description}</small></button>`; }).join("")}</div></section>`;
}

export function renderCreationClassStep(model: { classes: ClassDefinition[]; selectedClass: ClassDefinition; subclasses: SubclassDefinition[]; selectedSubclassId?: string; features: FeatureDefinition[] }, escapeHtml: EscapeHtml): string {
  const getFeature = (id: string) => model.features.find((feature) => feature.id === id);
  const renderFeatures = (label: string, ids: string[]) => {
    const entries = ids.map((id) => {
    const feature = getFeature(id);
      return feature ? `<article><strong>${escapeHtml(feature.name)}</strong><p>${escapeHtml(feature.summary)}</p></article>` : "";
    }).join("");
    return entries ? `<section class="character-subclass-feature-group"><span>${label}</span><div>${entries}</div></section>` : "";
  };
  return `<section class="character-class-picker creation-step-panel" data-creation-panel="5"><div><span>Arquétipo</span><h3>Classe e subclasse</h3><p>Escolha a classe e compare todas as Features de cada subclasse antes de decidir.</p></div><label class="form-field"><span>Classe</span><select data-character-class>${model.classes.map((definition) => `<option value="${escapeHtml(definition.id)}" ${definition.id === model.selectedClass.id ? "selected" : ""}>${escapeHtml(getClassDisplayName(definition))}</option>`).join("")}</select><small>${escapeHtml(model.selectedClass.summary)}</small></label><p class="character-class-starting-stats">Evasão inicial <strong>${model.selectedClass.startingEvasion}</strong><span>·</span> PV inicial <strong>${model.selectedClass.startingHitPoints}</strong></p><div class="character-subclass-choice-grid">${model.subclasses.map((subclass) => `<label class="character-subclass-choice ${subclass.id === model.selectedSubclassId ? "is-selected" : ""}"><input type="radio" name="character-subclass" data-character-subclass-id="${escapeHtml(subclass.id)}" ${subclass.id === model.selectedSubclassId ? "checked" : ""}/><span><strong>${escapeHtml(subclass.name)}</strong><small>${escapeHtml(subclass.summary)}</small>${subclass.spellcastAttributeId ? `<em>Conjuração: ${escapeHtml(characterCreationAttributes.find((attribute) => attribute.id === subclass.spellcastAttributeId)?.label ?? "")}</em>` : ""}<div class="character-subclass-features">${renderFeatures("Fundação", subclass.foundationFeatureIds)}${renderFeatures("Especialização", subclass.specializationFeatureIds)}${renderFeatures("Maestria", subclass.masteryFeatureIds)}</div></span></label>`).join("") || `<p class="form-error">Cadastre uma subclasse no Compendium.</p>`}</div></section>`;
}

export function renderCreationCommunityStep(model: { communities: CommunityDefinition[]; features: FeatureDefinition[]; selectedId?: string; search: string; packId: string; getPackDisplayName: (packId: string) => string }, escapeHtml: EscapeHtml): string {
  const selected = model.communities.find((community) => community.id === model.selectedId);
  const packs = [...new Set(model.communities.map((community) => community.packId))];
  const query = model.search.trim().toLocaleLowerCase("pt-BR");
  const visible = model.communities.filter((community) => (model.packId === "todos" || community.packId === model.packId) && (!query || `${community.name} ${community.summary} ${community.adjectives.join(" ")}`.toLocaleLowerCase("pt-BR").includes(query)));
  const renderChoice = (community: CommunityDefinition) => {
    const isSelected = community.id === selected?.id;
    const feature = isSelected ? model.features.find((entry) => entry.id === community.featureId) : undefined;
    return `<button type="button" class="character-community-choice ${isSelected ? "is-selected is-focused" : ""}" data-character-community-id="${escapeHtml(community.id)}" aria-pressed="${isSelected}"><strong>${escapeHtml(community.name)}</strong><small>${escapeHtml(community.summary)}</small>${isSelected ? `<span class="character-community-choice-benefit"><b>Benefício da comunidade</b><em>${escapeHtml(feature?.name ?? "Benefício indisponível")}</em><span>${escapeHtml(feature?.summary ?? "")}</span>${community.adjectives.length ? `<i>${community.adjectives.map((adjective) => escapeHtml(adjective)).join(" · ")}</i>` : ""}</span>` : ""}</button>`;
  };
  return `<section class="character-community-picker creation-step-panel" data-creation-panel="4"><div><span>Herança</span><p>Escolha a comunidade que moldou as relações, costumes e histórias do personagem.</p></div>${model.communities.length ? `<div class="character-community-filters"><label class="sf-search-field character-creation-search"><span aria-hidden="true">⌕</span><input type="search" data-character-community-search value="${escapeHtml(model.search)}" placeholder="Pesquisar comunidade" aria-label="Pesquisar comunidade" /></label><label class="form-field compact-select"><span>Pack</span><select data-character-community-pack-filter><option value="todos">Todos os Packs</option>${packs.map((packId) => `<option value="${escapeHtml(packId)}" ${packId === model.packId ? "selected" : ""}>${escapeHtml(packId === "local" ? "Local" : model.getPackDisplayName(packId))}</option>`).join("")}</select></label></div><div class="character-community-choice-grid">${visible.map(renderChoice).join("") || `<p class="form-error">Nenhuma comunidade encontrada.</p>`}</div>` : `<p class="form-error">Importe um Pack de comunidades antes de criar a ficha.</p>`}</section>`;
}

export function renderCreationReviewStep(model: { name: string; community: string; ancestries: string; topFeature?: string; bottomFeature?: string; attributes: Array<{ label: string; value: number }>; className: string; subclassName?: string; hitPoints: number; evasion: number; cards: string; experiences: string }, escapeHtml: EscapeHtml): string {
  const attributes = model.attributes.map((attribute) => `${attribute.label} ${attribute.value >= 0 ? "+" : ""}${attribute.value}`).join(" · ");
  return `<section class="character-creation-review creation-step-panel" data-creation-panel="9"><div><span>Pronto para começar</span><h3>${escapeHtml(model.name || "Sem nome")}</h3></div><div class="creation-review-grid"><article><span>Comunidade</span><strong>${escapeHtml(model.community || "Não definida")}</strong></article><article><span>Ancestralidades</span><strong>${escapeHtml(model.ancestries || "Não definida")}</strong></article><article><span>Top</span><strong>${escapeHtml(model.topFeature ?? "Não definida")}</strong></article><article><span>Bottom</span><strong>${escapeHtml(model.bottomFeature ?? "Não definida")}</strong></article><article><span>Atributos</span><strong>${escapeHtml(attributes)}</strong></article><article><span>Classe</span><strong>${escapeHtml(model.className)} · ${escapeHtml(model.subclassName ?? "Sem subclasse")}</strong><small>PV ${model.hitPoints} · Evasão ${model.evasion}</small></article><article><span>Cartas no Loadout</span><strong>${escapeHtml(model.cards || "Nenhuma carta")}</strong></article><article><span>Experiências +2</span><strong>${escapeHtml(model.experiences || "Não definidas")}</strong></article></div></section>`;
}
