import type { Attribute } from "../../domain/types";
import { characterCreationAttributes, formatCreationAttributeValue, getRemainingCreationAttributeValues } from "./attributeAllocation";

type EscapeHtml = (value: string) => string;

export function renderCreationIdentityStep(state: { name: string; community: string; portraitImage?: string }, escapeHtml: EscapeHtml): string {
  return `<div class="form-grid character-creation-identity creation-step-panel" data-creation-panel="1"><label class="form-field"><span>Nome</span><input data-character-name required maxlength="60" value="${escapeHtml(state.name)}" placeholder="Nome do personagem" /></label><label class="form-field form-field-wide"><span>Comunidade</span><input data-character-community required maxlength="80" value="${escapeHtml(state.community)}" placeholder="Ex.: Vigilia de Tristelo" /></label><label class="form-field form-field-wide character-portrait-upload"><span>Foto do personagem</span><input data-character-portrait type="file" accept="image/png,image/jpeg,image/webp" /><small>${state.portraitImage ? "Foto selecionada. Você pode escolher outra para substituí-la." : "Opcional. PNG, JPG ou WebP; até 1,5 MB."}</small>${state.portraitImage ? `<img src="${escapeHtml(state.portraitImage)}" alt="Prévia do retrato" />` : ""}</label></div>`;
}

export function renderCreationExperiencesStep(experiences: Array<{ name: string }>, escapeHtml: EscapeHtml): string {
  return `<section class="character-creation-experiences creation-step-panel" data-creation-panel="7"><div><span>História</span><h3>Defina duas Experiências</h3><p>Cada uma começa em +2. Escolha frases específicas que expressem vivências, aptidões ou traços do personagem.</p></div><div class="form-grid">${experiences.map((experience, index) => `<label class="form-field form-field-wide"><span>Experiência ${index + 1} · +2</span><input data-character-experience-name="${index}" maxlength="80" value="${escapeHtml(experience.name)}" placeholder="Ex.: Vigia de fronteira" /><small>Evite termos muito amplos ou que concedam um poder específico.</small></label>`).join("")}</div></section>`;
}

export function renderCreationAttributesStep(values: Record<Attribute["id"], number>): string {
  const available = getRemainingCreationAttributeValues(values);
  return `<section class="character-attributes-picker creation-step-panel" data-creation-panel="4"><div><span>Traços</span><p>Distribua seus atributos. Use cada valor uma vez: +2, +1, +1, +0, +0 e −1.</p><div class="character-attribute-available" aria-live="polite"><strong>Valores disponíveis</strong><span>${available.length ? available.map((value) => `<i>${formatCreationAttributeValue(value)}</i>`).join("") : "Todos distribuídos"}</span><button type="button" class="character-attribute-reset" data-action="reset-character-attributes">Resetar</button></div></div><div class="character-attribute-choice-grid">${characterCreationAttributes.map((attribute) => { const selected = values[attribute.id]; const remaining = getRemainingCreationAttributeValues(values, attribute.id); return `<label class="form-field"><span>${attribute.label}</span><small>${attribute.description}</small><select data-character-attribute-id="${attribute.id}"><option value="" ${Number.isNaN(selected) ? "selected" : ""}>Selecione</option>${[-1, 0, 1, 2].map((value) => `<option value="${value}" ${selected === value ? "selected" : ""} ${selected === value || remaining.includes(value) ? "" : "disabled"}>${formatCreationAttributeValue(value)}</option>`).join("")}</select></label>`; }).join("")}</div></section>`;
}

export function renderCreationReviewStep(model: { name: string; community: string; ancestries: string; topFeature?: string; bottomFeature?: string; attributes: Array<{ label: string; value: number }>; className: string; subclassName?: string; hitPoints: number; evasion: number; cards: string; experiences: string }, escapeHtml: EscapeHtml): string {
  const attributes = model.attributes.map((attribute) => `${attribute.label} ${attribute.value >= 0 ? "+" : ""}${attribute.value}`).join(" · ");
  return `<section class="character-creation-review creation-step-panel" data-creation-panel="8"><div><span>Pronto para começar</span><h3>${escapeHtml(model.name || "Sem nome")}</h3><p>${escapeHtml(model.community || "Comunidade não definida")}</p></div><div class="creation-review-grid"><article><span>Ancestralidades</span><strong>${escapeHtml(model.ancestries || "Não definida")}</strong></article><article><span>Top</span><strong>${escapeHtml(model.topFeature ?? "Não definida")}</strong></article><article><span>Bottom</span><strong>${escapeHtml(model.bottomFeature ?? "Não definida")}</strong></article><article><span>Atributos</span><strong>${escapeHtml(attributes)}</strong></article><article><span>Classe</span><strong>${escapeHtml(model.className)} · ${escapeHtml(model.subclassName ?? "Sem subclasse")}</strong><small>PV ${model.hitPoints} · Evasão ${model.evasion}</small></article><article><span>Cartas no Loadout</span><strong>${escapeHtml(model.cards || "Nenhuma carta")}</strong></article><article><span>Experiências +2</span><strong>${escapeHtml(model.experiences || "Não definidas")}</strong></article></div></section>`;
}
