import type { Catalog } from "../../domain/catalog";
import type { AncestryDefinition, FeatureDefinition } from "../../domain/types";

export type AncestryFeatureState = { compendiumAncestrySearch: string; ancestryModalOpen: boolean; editingCompendiumAncestryId?: string; deletingCompendiumAncestryId?: string };
export type AncestryFeatureDependencies = { state: AncestryFeatureState; catalog: Catalog; escapeHtml: (value: string) => string; renderEmptyInline: (message: string) => string; getPackDisplayName: (packId: string) => string; saveCustomDefinition: (definition: AncestryDefinition | FeatureDefinition) => Promise<void>; deleteCustomDefinition: (definitionId: string) => Promise<void>; refreshCatalog: () => Promise<void>; render: () => void };

export function renderCompendiumAncestriesManager(deps: AncestryFeatureDependencies): string {
  const search = deps.state.compendiumAncestrySearch.trim().toLocaleLowerCase("pt-BR");
  const entries = [...deps.catalog.ancestries].filter((entry) => !search || `${entry.name} ${entry.summary}`.toLocaleLowerCase("pt-BR").includes(search)).sort((left, right) => left.name.localeCompare(right.name, "pt-BR"));
  return `<main class="content compendium-content"><div class="screen-title"><div><h1>Ancestralidades</h1><p>Defina linhagens reutilizaveis e as duas features que cada uma concede.</p></div><button class="secondary-action screen-title-action" type="button" data-action="back-compendium-index">Voltar ao indice</button></div><section class="compendium-management-panel"><div class="compendium-management-toolbar"><div class="management-copy"><span>HERANCA</span><strong>${deps.catalog.ancestries.length} ${deps.catalog.ancestries.length === 1 ? "ancestralidade" : "ancestralidades"}</strong></div><label class="search-box"><span aria-hidden="true">⌕</span><input type="search" data-compendium-ancestry-search value="${deps.escapeHtml(deps.state.compendiumAncestrySearch)}" placeholder="Pesquisar ancestralidade" aria-label="Pesquisar ancestralidade" /></label><button class="primary-action" type="button" data-action="new-compendium-ancestry">Nova ancestralidade</button></div>${entries.length ? `<div class="compendium-ancestry-results">${entries.map((entry) => renderAncestryResult(entry, deps)).join("")}</div>` : deps.renderEmptyInline(search ? "Nenhuma ancestralidade corresponde a esta pesquisa." : "Nenhuma ancestralidade cadastrada. Crie a primeira para disponibilizar suas Top e Bottom Features na criacao de personagens.")}</section></main>`;
}

export function renderCompendiumAncestryFormModal(deps: AncestryFeatureDependencies): string {
  if (!deps.state.ancestryModalOpen) return "";
  const ancestry = deps.state.editingCompendiumAncestryId ? deps.catalog.ancestries.find((entry) => entry.id === deps.state.editingCompendiumAncestryId) : undefined;
  const top = ancestry ? feature(ancestry, "top", deps.catalog) : undefined;
  const bottom = ancestry ? feature(ancestry, "bottom", deps.catalog) : undefined;
  return `<div class="modal-backdrop" data-modal-backdrop><form class="modal ancestry-form-modal" onsubmit="return false;" aria-labelledby="ancestry-form-title"><button class="modal-close" type="button" data-modal-close aria-label="Fechar">×</button><div class="modal-title"><span>Compendium</span><h2 id="ancestry-form-title">${ancestry ? "Editar ancestralidade" : "Nova ancestralidade"}</h2><p>As duas features ficam ordenadas para suportar escolhas unicas e mistas.</p></div><label class="form-field"><span>Nome</span><input data-ancestry-name required value="${deps.escapeHtml(ancestry?.name ?? "")}" /></label><label class="form-field"><span>Descricao</span><textarea data-ancestry-summary required>${deps.escapeHtml(ancestry?.summary ?? "")}</textarea></label><label class="form-field"><span>Imagem (opcional)</span><input data-ancestry-image type="file" accept="image/*" />${ancestry?.image ? "<small>A imagem atual sera mantida se nenhum arquivo for escolhido.</small>" : ""}</label>${featureFields("Top", top, "top", deps)}${featureFields("Bottom", bottom, "bottom", deps)}<p class="form-error" data-ancestry-error hidden></p><div class="modal-actions"><button class="secondary-action" type="button" data-modal-close>Cancelar</button><button class="primary-action" type="button" data-action="save-compendium-ancestry">Salvar ancestralidade</button></div></form></div>`;
}

export function renderDeleteCompendiumAncestryModal(deps: AncestryFeatureDependencies): string {
  const ancestry = deps.state.deletingCompendiumAncestryId ? deps.catalog.ancestries.find((entry) => entry.id === deps.state.deletingCompendiumAncestryId) : undefined;
  return ancestry ? `<div class="modal-backdrop" data-modal-backdrop><section class="modal confirm-modal"><h2>Excluir ancestralidade?</h2><p>"${deps.escapeHtml(ancestry.name)}" e suas duas features serao removidas deste dispositivo. Personagens que futuramente a referenciarem poderao perder essas referencias.</p><div class="modal-actions"><button class="secondary-action" type="button" data-action="cancel-delete-compendium-ancestry">Cancelar</button><button class="danger-action" type="button" data-action="confirm-delete-compendium-ancestry">Excluir</button></div></section></div>` : "";
}

export async function saveCompendiumAncestry(deps: AncestryFeatureDependencies): Promise<void> {
  const value = (selector: string) => document.querySelector<HTMLInputElement | HTMLTextAreaElement>(selector)?.value.trim() ?? "";
  const name = value("[data-ancestry-name]"); const summary = value("[data-ancestry-summary]"); const topName = value("[data-ancestry-top-name]"); const topSummary = value("[data-ancestry-top-summary]"); const bottomName = value("[data-ancestry-bottom-name]"); const bottomSummary = value("[data-ancestry-bottom-summary]");
  const error = document.querySelector<HTMLElement>("[data-ancestry-error]");
  const existing = deps.state.editingCompendiumAncestryId ? deps.catalog.ancestries.find((entry) => entry.id === deps.state.editingCompendiumAncestryId) : undefined;
  const duplicate = deps.catalog.ancestries.some((entry) => entry.name.toLocaleLowerCase("pt-BR") === name.toLocaleLowerCase("pt-BR") && entry.id !== existing?.id);
  if (!name || !summary || !topName || !topSummary || !bottomName || !bottomSummary || duplicate) { if (error) { error.hidden = false; error.textContent = duplicate ? "Ja existe uma ancestralidade com este nome." : "Preencha a ancestralidade e as duas features."; } return; }
  if (existing && existing.packId !== "local") return;
  try {
    const image = (await readImage("[data-ancestry-image]")) ?? existing?.image; const id = existing?.id ?? `ancestry.local.${crypto.randomUUID()}`;
    const topId = (existing ? feature(existing, "top", deps.catalog)?.id : undefined) ?? `feature.local.${crypto.randomUUID()}`; const bottomId = (existing ? feature(existing, "bottom", deps.catalog)?.id : undefined) ?? `feature.local.${crypto.randomUUID()}`;
    const ancestry: AncestryDefinition = { id, type: "ancestry", packId: "local", name, summary, image, topFeatureId: topId, bottomFeatureId: bottomId };
    const top: FeatureDefinition = { id: topId, type: "feature", packId: "local", name: topName, summary: topSummary, sourceType: "ancestry", sourceId: id, tier: "top", ...resourceModifier("top") };
    const bottom: FeatureDefinition = { id: bottomId, type: "feature", packId: "local", name: bottomName, summary: bottomSummary, sourceType: "ancestry", sourceId: id, tier: "bottom", ...resourceModifier("bottom") };
    await Promise.all([deps.saveCustomDefinition(ancestry), deps.saveCustomDefinition(top), deps.saveCustomDefinition(bottom)]); await deps.refreshCatalog(); deps.state.ancestryModalOpen = false; deps.state.editingCompendiumAncestryId = undefined; deps.render();
  } catch (caught) { if (error) { error.hidden = false; error.textContent = caught instanceof Error ? caught.message : "Nao foi possivel salvar a ancestralidade."; } }
}

export async function removeCompendiumAncestry(deps: AncestryFeatureDependencies): Promise<void> {
  const ancestry = deps.state.deletingCompendiumAncestryId ? deps.catalog.ancestries.find((entry) => entry.id === deps.state.deletingCompendiumAncestryId) : undefined;
  if (!ancestry || ancestry.packId !== "local") return;
  await Promise.all([ancestry.id, ancestry.topFeatureId, ancestry.bottomFeatureId].map((id) => deps.deleteCustomDefinition(id))); await deps.refreshCatalog(); deps.state.deletingCompendiumAncestryId = undefined; deps.render();
}

function renderAncestryResult(ancestry: AncestryDefinition, deps: AncestryFeatureDependencies): string {
  const top = feature(ancestry, "top", deps.catalog); const bottom = feature(ancestry, "bottom", deps.catalog); const local = ancestry.packId === "local"; const source = local ? "Local" : deps.getPackDisplayName(ancestry.packId);
  return `<article class="compendium-class-result compendium-ancestry-result"><div class="compendium-class-result-open compendium-ancestry-result-open">${ancestry.image ? `<span class="compendium-class-image" style="background-image: url('${deps.escapeHtml(ancestry.image)}')"></span>` : '<span class="compendium-class-image class-image-placeholder">ANCESTRALIDADE</span>'}<span class="compendium-class-body"><span>${deps.escapeHtml(source)}</span><h2>${deps.escapeHtml(ancestry.name)}</h2><p>${deps.escapeHtml(ancestry.summary)}</p><span class="ancestry-feature-pair"><span><b>Top Feature</b><strong>${deps.escapeHtml(top?.name ?? "Feature indisponivel")}</strong><small>${deps.escapeHtml(top?.summary ?? "")}</small></span><span><b>Bottom Feature</b><strong>${deps.escapeHtml(bottom?.name ?? "Feature indisponivel")}</strong><small>${deps.escapeHtml(bottom?.summary ?? "")}</small></span></span></span></div><div class="compendium-card-result-actions">${local ? `<button type="button" data-action="edit-compendium-ancestry" data-ancestry-id="${deps.escapeHtml(ancestry.id)}">Editar</button><button type="button" data-action="delete-compendium-ancestry" data-ancestry-id="${deps.escapeHtml(ancestry.id)}">Excluir</button>` : '<span class="readonly-label">Conteúdo não editável</span>'}</div></article>`;
}

function feature(ancestry: AncestryDefinition, position: "top" | "bottom", catalog: Catalog): FeatureDefinition | undefined { return catalog.features.find((entry) => entry.id === (position === "top" ? ancestry.topFeatureId : ancestry.bottomFeatureId)); }
function featureFields(label: string, definition: FeatureDefinition | undefined, key: "top" | "bottom", deps: AncestryFeatureDependencies): string {
  const modifier = definition?.sheetModifiers?.find((entry) => entry.kind === "resource-max");
  return `<div class="ancestry-feature-form-grid"><fieldset class="class-domain-field"><legend>${label} Feature</legend><label class="form-field"><span>Nome</span><input data-ancestry-${key}-name required value="${deps.escapeHtml(definition?.name ?? "")}"/></label><label class="form-field"><span>Descricao</span><textarea data-ancestry-${key}-summary required>${deps.escapeHtml(definition?.summary ?? "")}</textarea></label><div class="form-grid"><label class="form-field"><span>Bônus de recurso</span><select data-ancestry-${key}-modifier-kind><option value="none" ${modifier ? "" : "selected"}>Nenhum</option><option value="resource-max" ${modifier ? "selected" : ""}>Aumentar máximo</option></select></label><label class="form-field"><span>Recurso</span><select data-ancestry-${key}-resource-id><option value="hp" ${modifier?.resourceId === "hp" ? "selected" : ""}>PV</option><option value="stress" ${modifier?.resourceId === "stress" ? "selected" : ""}>Estresse</option><option value="hope" ${modifier?.resourceId === "hope" ? "selected" : ""}>Esperança</option><option value="armor-slots" ${modifier?.resourceId === "armor-slots" ? "selected" : ""}>Armadura</option></select></label><label class="form-field"><span>Quantidade</span><input data-ancestry-${key}-resource-amount type="number" min="1" step="1" value="${modifier?.amount ?? 1}" /></label></div><small>O bônus é aplicado automaticamente enquanto esta Feature estiver selecionada.</small></fieldset></div>`;
}
function resourceModifier(key: "top" | "bottom"): Pick<FeatureDefinition, "sheetModifiers"> { const kind = document.querySelector<HTMLSelectElement>(`[data-ancestry-${key}-modifier-kind]`)?.value; if (kind !== "resource-max") return {}; const resourceId = document.querySelector<HTMLSelectElement>(`[data-ancestry-${key}-resource-id]`)?.value ?? "stress"; const amount = Number(document.querySelector<HTMLInputElement>(`[data-ancestry-${key}-resource-amount]`)?.value ?? 0); return Number.isFinite(amount) && amount > 0 ? { sheetModifiers: [{ kind: "resource-max", resourceId, amount }] } : {}; }
function readImage(selector: string): Promise<string | undefined> { const file = document.querySelector<HTMLInputElement>(selector)?.files?.[0]; if (!file) return Promise.resolve(undefined); if (file.size > 1_500_000) return Promise.reject(new Error("A imagem deve ter no maximo 1,5 MB.")); return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(typeof reader.result === "string" ? reader.result : undefined); reader.onerror = () => reject(new Error("Nao foi possivel ler a imagem.")); reader.readAsDataURL(file); }); }
