import type { Catalog } from "../../domain/catalog";
import type { ClassDefinition, FeatureDefinition, SubclassDefinition } from "../../domain/types";

export type ClassFeatureState = { classModalOpen: boolean; editingCompendiumClassId?: string; deletingCompendiumClassId?: string; compendiumClassPreviewId?: string };
export type ClassFeatureDependencies = { state: ClassFeatureState; catalog: Catalog; escapeHtml: (value: string) => string; renderEmptyInline: (message: string) => string; saveCustomDefinition: (definition: ClassDefinition | FeatureDefinition | SubclassDefinition) => Promise<void>; deleteCustomDefinition: (definitionId: string) => Promise<void>; refreshCatalog: () => Promise<void>; render: () => void };

export function renderCompendiumClassesManager(deps: ClassFeatureDependencies): string {
  const classes = [...deps.catalog.classes].sort((a,b)=>a.name.localeCompare(b.name,"pt-BR"));
  return `<main class="content compendium-content"><div class="screen-title"><div><h1>Classes</h1><p>Defina quais dominios cada classe pode usar ao montar o deck de um personagem.</p></div><button class="secondary-action screen-title-action" type="button" data-action="back-compendium-index">Voltar ao indice</button></div><section class="compendium-management-panel"><div class="compendium-management-toolbar"><div class="management-copy"><span>BASE DO COMPENDIUM</span><strong>${classes.length} ${classes.length===1?"classe":"classes"}</strong></div><button class="primary-action" type="button" data-action="new-compendium-class">Nova classe</button></div>${classes.length?`<div class="compendium-class-results">${classes.map(c=>renderClassResult(c,deps)).join("")}</div>`:deps.renderEmptyInline("Nenhuma classe cadastrada. Crie a primeira classe para definir seus dominios, valores iniciais e subclasses.")}</section></main>`;
}

export function renderCompendiumClassPreviewModal(deps: ClassFeatureDependencies): string {
  const definition=deps.state.compendiumClassPreviewId?deps.catalog.classes.find(c=>c.id===deps.state.compendiumClassPreviewId):undefined; if(!definition)return "";
  const domains=definition.domainIds.map(id=>deps.catalog.domains.find(d=>d.id===id)).filter(Boolean); const subclasses=getClassSubclasses(definition,deps.catalog);
  const tabs=subclasses.length?`<div class="class-detail-subclass-tabs"><div class="class-detail-subclass-tab-list" role="tablist" aria-label="Subclasses">${subclasses.map((s,i)=>`<button class="${i===0?"is-active":""}" type="button" role="tab" aria-selected="${i===0}" data-action="select-class-detail-subclass-tab" data-subclass-tab="${i}">${deps.escapeHtml(s.name)}</button>`).join("")}</div><div class="class-detail-subclass-panels">${subclasses.map((s,i)=>`<article class="class-detail-subclass-panel ${i===0?"is-active":""}">${s.summary?`<p>${deps.escapeHtml(s.summary)}</p>`:""}<div class="class-detail-feature-grid">${renderFeatureDetail(getFeature(s.foundationFeatureIds[0],deps.catalog),"Fundacao",deps)}${renderFeatureDetail(getFeature(s.specializationFeatureIds[0],deps.catalog),"Especializacao",deps)}${renderFeatureDetail(getFeature(s.masteryFeatureIds[0],deps.catalog),"Maestria",deps)}</div></article>`).join("")}</div></div>`:'<p class="class-detail-summary">Nenhuma subclasse cadastrada.</p>';
  return `<div class="modal-backdrop" data-modal-backdrop><section class="class-detail-modal" role="dialog" aria-modal="true" aria-labelledby="class-detail-title"><button class="modal-close" data-modal-close aria-label="Fechar detalhes da classe">x</button><div class="class-detail-art ${definition.image?"has-image":""}" ${definition.image?`style="background-image: url('${deps.escapeHtml(definition.image)}')"`:""}>${definition.image?"":"CLASSE"}</div><div class="class-detail-body"><span class="resource-modal-label">Classe</span><h2 id="class-detail-title">${deps.escapeHtml(definition.name)}</h2><p class="class-detail-summary">${deps.escapeHtml(definition.summary)}</p><div class="class-detail-stats"><span>Evasao inicial <strong>${getStartingEvasion(definition)}</strong></span><span>HP inicial <strong>${definition.startingHitPoints}</strong></span></div><section class="class-detail-section"><h3>Dominios</h3><div class="class-domain-list">${domains.map(d=>`<i style="--domain-color: ${deps.escapeHtml(d!.color)}">${deps.escapeHtml(d!.name)}</i>`).join("")}</div></section><section class="class-detail-section"><h3>Caracteristicas da classe</h3><div class="class-detail-feature-grid">${renderFeatureDetail(getFeature(definition.featureIds[0],deps.catalog),"Caracteristica de classe",deps)}${renderFeatureDetail(getFeature(definition.hopeFeatureId,deps.catalog),"Caracteristica de Esperanca",deps)}</div></section><section class="class-detail-section"><h3>Subclasses</h3>${tabs}</section></div></section></div>`;
}

export function renderCompendiumClassFormModal(deps: ClassFeatureDependencies): string {
  if(!deps.state.classModalOpen)return ""; const c=deps.state.editingCompendiumClassId?deps.catalog.classes.find(x=>x.id===deps.state.editingCompendiumClassId):undefined; const selected=new Set(c?.domainIds??[]); const subs=c?getClassSubclasses(c,deps.catalog):[];
  return `<div class="modal-backdrop" data-modal-backdrop><section class="form-modal class-form-modal" role="dialog" aria-modal="true" aria-labelledby="class-form-title"><button class="modal-close" data-modal-close aria-label="Fechar classe">x</button><h2 id="class-form-title">${c?"Editar classe":"Nova classe"}</h2><p>Defina a identidade inicial e as duas subclasses desta classe.</p><div class="form-grid class-core-fields"><label class="form-field"><span>Nome *</span><input data-compendium-class-name value="${deps.escapeHtml(c?.name??"")}" placeholder="Ex.: Guardiao" /></label><label class="form-field"><span>Evasao inicial *</span><input data-compendium-class-starting-evasion type="number" min="0" step="1" value="${c?getStartingEvasion(c):""}" /></label><label class="form-field"><span>HP inicial *</span><input data-compendium-class-starting-hp type="number" min="1" step="1" value="${c?.startingHitPoints??""}" /></label></div><label class="form-field"><span>Imagem</span><input data-compendium-class-image type="file" accept="image/png,image/jpeg,image/webp" /></label><fieldset class="class-domain-field"><legend>Dominios liberados * <small>Escolha exatamente dois.</small></legend><div>${deps.catalog.domains.map(d=>`<label style="--domain-color: ${deps.escapeHtml(d.color)}"><input type="checkbox" data-compendium-class-domain value="${d.id}" ${selected.has(d.id)?"checked":""}/><span>${deps.escapeHtml(d.name)}</span></label>`).join("")}</div></fieldset><label class="form-field"><span>Descricao *</span><textarea data-compendium-class-summary>${deps.escapeHtml(c?.summary??"")}</textarea></label>${renderFeatureFields("class","Caracteristica de classe",c?getFeature(c.featureIds[0],deps.catalog):undefined,true,deps)}${renderFeatureFields("hope","Caracteristica de Esperanca",c?getFeature(c.hopeFeatureId,deps.catalog):undefined,true,deps,"Ativada ao gastar 3 Esperancas.")}<fieldset class="class-subclasses-field"><legend>Subclasses * <small>Uma classe possui exatamente duas subclasses.</small></legend><div class="class-subclass-tabs"><div class="class-subclass-tab-list" role="tablist"><button class="is-active" type="button" data-action="select-class-subclass-tab" data-subclass-tab="0">Subclasse 1</button><button type="button" data-action="select-class-subclass-tab" data-subclass-tab="1">Subclasse 2</button></div><div class="class-subclass-panels"><div class="class-subclass-tab-panel class-subclass-tab-panel-0 is-active">${renderSubclassFields(0,subs[0],deps)}</div><div class="class-subclass-tab-panel class-subclass-tab-panel-1">${renderSubclassFields(1,subs[1],deps)}</div></div></div></fieldset><p class="form-error" data-compendium-class-error hidden></p><div class="modal-actions icon-modal-actions"><button class="secondary-action icon-action" type="button" data-modal-close>↩</button><button class="primary-action icon-action" type="button" data-action="save-compendium-class">🪶</button></div></section></div>`;
}

export function renderDeleteCompendiumClassModal(deps: ClassFeatureDependencies): string { const c=deps.state.deletingCompendiumClassId?deps.catalog.classes.find(x=>x.id===deps.state.deletingCompendiumClassId):undefined; return c?`<div class="modal-backdrop" data-modal-backdrop><section class="confirm-modal"><h2>Excluir classe?</h2><p>A classe <strong>${deps.escapeHtml(c.name)}</strong> sera removida deste dispositivo.</p><div class="modal-actions"><button class="secondary-action" type="button" data-action="cancel-delete-compendium-class">Cancelar</button><button class="danger-action" type="button" data-action="confirm-delete-compendium-class">Excluir</button></div></section></div>`:""; }

export async function saveCompendiumClass(deps: ClassFeatureDependencies): Promise<void> {
  const value=(s:string)=>document.querySelector<HTMLInputElement|HTMLTextAreaElement>(s)?.value.trim()??""; const {state,catalog}=deps; const name=value("[data-compendium-class-name]"),summary=value("[data-compendium-class-summary]"),evasion=Number(value("[data-compendium-class-starting-evasion]")),hp=Number(value("[data-compendium-class-starting-hp]")),domains=Array.from(document.querySelectorAll<HTMLInputElement>("[data-compendium-class-domain]:checked")).map(x=>x.value),error=document.querySelector<HTMLElement>("[data-compendium-class-error]"); const existing=state.editingCompendiumClassId?catalog.classes.find(x=>x.id===state.editingCompendiumClassId):undefined; const duplicate=catalog.classes.some(x=>x.name.toLocaleLowerCase("pt-BR")===name.toLocaleLowerCase("pt-BR")&&x.id!==existing?.id); const main=readFeature("class","class","class",existing?.featureIds[0]),hope=readFeature("hope","class","hope",existing?.hopeFeatureId,3),drafts=[0,1].map(i=>readSubclass(i,existing?.subclassIds[i],catalog));
  if(!name||!summary||domains.length!==2||new Set(domains).size!==2||!Number.isInteger(evasion)||evasion<0||!Number.isInteger(hp)||hp<1||!main||!hope||drafts.some(s=>!s.name||!s.foundation)||duplicate){if(error){error.hidden=false;error.textContent=duplicate?"Ja existe uma classe com este nome.":"Informe nome, descricao, evasao, HP, duas caracteristicas, exatamente dois dominios e duas subclasses com Fundacao.";}return;} if(existing&&existing.packId!=="local")return;
  let image=existing?.image; try{image=(await readImage("[data-compendium-class-image]"))??image;}catch(e){if(error){error.hidden=false;error.textContent=e instanceof Error?e.message:"Nao foi possivel usar a imagem.";}return;} const id=existing?.id??`class.local.${crypto.randomUUID()}`; const features:FeatureDefinition[]=[{...main,sourceId:id},{...hope,sourceId:id}]; const subclasses:SubclassDefinition[]=drafts.map(d=>{const sid=d.id??`subclass.local.${crypto.randomUUID()}`,f={...d.foundation!,sourceId:sid},s=d.specialization?{...d.specialization,sourceId:sid}:undefined,m=d.mastery?{...d.mastery,sourceId:sid}:undefined;features.push(f,...(s?[s]:[]),...(m?[m]:[]));return{id:sid,type:"subclass",packId:"local",name:d.name,summary:d.summary,classId:id,foundationFeatureIds:[f.id],specializationFeatureIds:s?[s.id]:[],masteryFeatureIds:m?[m.id]:[]};}); const definition:ClassDefinition={id,type:"class",packId:"local",name,summary,domainIds:[domains[0],domains[1]],startingEvasion:evasion,startingHitPoints:hp,featureIds:[main.id],hopeFeatureId:hope.id,subclassIds:[subclasses[0].id,subclasses[1].id],image}; await deps.saveCustomDefinition(definition);await Promise.all([...subclasses,...features].map(x=>deps.saveCustomDefinition(x)));await deps.refreshCatalog();state.classModalOpen=false;state.editingCompendiumClassId=undefined;deps.render();
}

export async function removeCompendiumClass(deps: ClassFeatureDependencies): Promise<void>{const c=deps.state.deletingCompendiumClassId?deps.catalog.classes.find(x=>x.id===deps.state.deletingCompendiumClassId):undefined;if(!c||c.packId!=="local")return;const subs=deps.catalog.subclasses.filter(s=>s.classId===c.id&&s.packId==="local"),ids=new Set([c.hopeFeatureId,...c.featureIds,...subs.flatMap(s=>[...s.foundationFeatureIds,...s.specializationFeatureIds,...s.masteryFeatureIds])].filter(Boolean));await Promise.all([c.id,...subs.map(s=>s.id),...ids].map(id=>deps.deleteCustomDefinition(id)));await deps.refreshCatalog();deps.state.deletingCompendiumClassId=undefined;deps.render();}

function renderClassResult(c:ClassDefinition,deps:ClassFeatureDependencies):string{const domains=c.domainIds.map(id=>deps.catalog.domains.find(d=>d.id===id)).filter(Boolean),subs=getClassSubclasses(c,deps.catalog);return `<article class="compendium-class-result"><button class="compendium-class-result-open" type="button" data-compendium-class-preview-id="${c.id}">${c.image?`<span class="compendium-class-image" style="background-image: url('${deps.escapeHtml(c.image)}')"></span>`:'<span class="compendium-class-image class-image-placeholder">CLASSE</span>'}<span class="compendium-class-body"><span>${c.packId==="local"?"Local":"Pack"}</span><h2>${deps.escapeHtml(c.name)}</h2><p>${deps.escapeHtml(c.summary)}</p><span class="class-starting-stats"><span>Evasao inicial <strong>${getStartingEvasion(c)}</strong></span><span>HP inicial <strong>${c.startingHitPoints??"-"}</strong></span></span><span class="class-domain-list">${domains.map(d=>`<i style="--domain-color: ${deps.escapeHtml(d!.color)}">${deps.escapeHtml(d!.name)}</i>`).join("")}</span>${subs.length?`<span class="class-subclass-list"><b>Subclasses</b>${subs.map(s=>`<span>${deps.escapeHtml(s.name)}</span>`).join("")}</span>`:""}</span></button><div class="compendium-card-result-actions">${c.packId==="local"?`<button type="button" data-action="edit-compendium-class" data-class-id="${c.id}">Editar</button><button type="button" data-action="delete-compendium-class" data-class-id="${c.id}">Excluir</button>`:'<span class="readonly-label">Conteudo do pack</span>'}</div></article>`;}
function getFeature(id:string|undefined,c:Catalog){return id?c.features.find(f=>f.id===id):undefined;} function getClassSubclasses(c:ClassDefinition,catalog:Catalog){return(c.subclassIds??[]).map(id=>catalog.subclasses.find(s=>s.id===id)).filter((s):s is SubclassDefinition=>Boolean(s));} function getStartingEvasion(c:ClassDefinition){return c.startingEvasion??(c as ClassDefinition&{baseEvasion?:number}).baseEvasion??0;} function renderFeatureDetail(f:FeatureDefinition|undefined,label:string,deps:ClassFeatureDependencies){return f?`<article class="class-detail-feature"><span>${label}</span><h3>${deps.escapeHtml(f.name)}</h3><p>${deps.escapeHtml(f.summary)}</p>${f.hopeCost?`<small>Custo: ${f.hopeCost} Esperancas</small>`:""}</article>`:"";}
function renderFeatureFields(key:string,title:string,f:FeatureDefinition|undefined,required:boolean,deps:ClassFeatureDependencies,note?:string){return `<fieldset class="class-feature-field"><legend>${title}${required?" *":""}</legend>${note?`<small>${note}</small>`:""}<label class="form-field"><span>Nome${required?" *":""}</span><input data-class-feature-name="${key}" value="${deps.escapeHtml(f?.name??"")}"/></label><label class="form-field"><span>Descricao${required?" *":""}</span><textarea data-class-feature-summary="${key}">${deps.escapeHtml(f?.summary??"")}</textarea></label></fieldset>`;} function renderSubclassFields(i:number,s:SubclassDefinition|undefined,deps:ClassFeatureDependencies){return `<section class="class-subclass-editor"><label class="form-field"><span>Nome *</span><input data-class-subclass-name="${i}" value="${deps.escapeHtml(s?.name??"")}"/></label><label class="form-field"><span>Descricao</span><textarea data-class-subclass-summary="${i}">${deps.escapeHtml(s?.summary??"")}</textarea></label>${renderFeatureFields(`subclass-${i}-foundation`,"Fundacao",getFeature(s?.foundationFeatureIds[0],deps.catalog),true,deps)}${renderFeatureFields(`subclass-${i}-specialization`,"Especializacao",getFeature(s?.specializationFeatureIds[0],deps.catalog),false,deps)}${renderFeatureFields(`subclass-${i}-mastery`,"Maestria",getFeature(s?.masteryFeatureIds[0],deps.catalog),false,deps)}</section>`;}
function readFeature(key:string,sourceType:FeatureDefinition["sourceType"],tier:FeatureDefinition["tier"],existingId?:string,hopeCost?:number){const val=(s:string)=>document.querySelector<HTMLInputElement|HTMLTextAreaElement>(s)?.value.trim()??"",name=val(`[data-class-feature-name="${key}"]`),summary=val(`[data-class-feature-summary="${key}"]`);return name&&summary?{id:existingId??`feature.local.${crypto.randomUUID()}`,type:"feature" as const,packId:"local" as const,name,summary,sourceType,sourceId:"",tier,...(hopeCost?{hopeCost}:{})}:undefined;} function readSubclass(i:number,id:string|undefined,c:Catalog){const s=id?c.subclasses.find(x=>x.id===id):undefined,val=(q:string)=>document.querySelector<HTMLInputElement|HTMLTextAreaElement>(q)?.value.trim()??"";return{id:s?.id,name:val(`[data-class-subclass-name="${i}"]`),summary:val(`[data-class-subclass-summary="${i}"]`),foundation:readFeature(`subclass-${i}-foundation`,"subclass","foundation",s?.foundationFeatureIds[0]),specialization:readFeature(`subclass-${i}-specialization`,"subclass","specialization",s?.specializationFeatureIds[0]),mastery:readFeature(`subclass-${i}-mastery`,"subclass","mastery",s?.masteryFeatureIds[0])};} function readImage(q:string):Promise<string|undefined>{const f=document.querySelector<HTMLInputElement>(q)?.files?.[0];if(!f)return Promise.resolve(undefined);if(f.size>1_500_000)return Promise.reject(new Error("A imagem deve ter no maximo 1,5 MB."));return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(typeof r.result==="string"?r.result:undefined);r.onerror=()=>reject(new Error("Nao foi possivel ler a imagem."));r.readAsDataURL(f);});}
