import type { Catalog } from "../../domain/catalog";
import type { CommunityDefinition, FeatureDefinition } from "../../domain/types";
import { readFeatureAuthoringFields, renderFeatureAuthoringFields } from "./featureAuthoring";

export type CommunityFeatureState = { compendiumCommunitySearch: string; compendiumCommunityPackId: string; communityModalOpen: boolean; editingCompendiumCommunityId?: string; deletingCompendiumCommunityId?: string; compendiumCommunityPreviewId?: string };
export type CommunityFeatureDependencies = { state: CommunityFeatureState; catalog: Catalog; escapeHtml: (value: string) => string; getPackDisplayName: (packId: string) => string; saveCustomDefinition: (definition: CommunityDefinition | FeatureDefinition) => Promise<void>; deleteCustomDefinition: (id: string) => Promise<void>; refreshCatalog: () => Promise<void>; render: () => void };
type ChapterCard = { eyebrow: string; title: string; summary: string; count: number; countLabel: string; primaryAction: string; secondaryAction: string; details: string[] };

export function renderCompendiumCommunitiesManager(deps: CommunityFeatureDependencies): string {
  const allCommunities = [...deps.catalog.communities].sort((left, right) => left.name.localeCompare(right.name, "pt-BR"));
  const communities = filterCommunities(allCommunities, deps.state.compendiumCommunitySearch, deps.state.compendiumCommunityPackId);
  const packs = [...new Set(allCommunities.map((community) => community.packId))];
  return `<main class="content compendium-content"><div class="screen-title compendium-index-heading"><div><div class="compendium-index-title-row"><h1>Comunidades</h1><span class="compendium-index-count">${allCommunities.length} ${allCommunities.length === 1 ? "comunidade" : "comunidades"}</span></div><p>Origens culturais, sociais ou ambientais que concedem uma Feature.</p></div><div class="compendium-index-heading-actions"><button class="sf-action sf-action--primary primary-action" type="button" data-action="new-compendium-community">Nova comunidade</button><button class="sf-action sf-action--secondary secondary-action screen-title-action" type="button" data-action="back-compendium-index">Voltar ao índice</button></div></div><section class="compendium-book-index compendium-community-index"><div class="compendium-index-controls"><label class="sf-search-field search-box compendium-index-search"><span aria-hidden="true">⌕</span><input type="search" data-compendium-community-search value="${deps.escapeHtml(deps.state.compendiumCommunitySearch)}" placeholder="Pesquisar comunidade" aria-label="Pesquisar comunidade" /></label><label class="form-field compact-select"><span>Pack</span><select data-compendium-community-pack-filter><option value="todos">Todos os Packs</option>${packs.map((packId) => `<option value="${deps.escapeHtml(packId)}" ${packId === deps.state.compendiumCommunityPackId ? "selected" : ""}>${deps.escapeHtml(packId === "local" ? "Local" : deps.getPackDisplayName(packId))}</option>`).join("")}</select></label></div>${communities.length ? `<div class="compendium-ancestry-results">${communities.map((community) => renderCommunityResult(community, deps)).join("")}</div>` : `<div class="empty-state"><h2>Nenhuma comunidade encontrada</h2><p>Altere a busca ou o Pack selecionado.</p></div>`}</section></main>${renderCompendiumCommunityFormModal(deps)}${renderDeleteCompendiumCommunityModal(deps)}${renderCompendiumCommunityPreviewModal(deps)}`;
}

export function renderCompendiumCommunityPreviewModal(deps: CommunityFeatureDependencies): string {
  const community = deps.state.compendiumCommunityPreviewId ? deps.catalog.communities.find((entry) => entry.id === deps.state.compendiumCommunityPreviewId) : undefined;
  if (!community) return "";
  const feature = deps.catalog.features.find((entry) => entry.id === community.featureId);
  return `<div class="modal-backdrop" data-modal-backdrop><section class="compendium-entry-detail-modal compendium-community-detail-modal" role="dialog" aria-modal="true" aria-labelledby="community-detail-title"><button class="modal-close" type="button" data-modal-close aria-label="Fechar detalhes da comunidade">x</button><div class="compendium-entry-detail-art" aria-hidden="true">✦</div><div class="compendium-entry-detail-body"><span class="resource-modal-label">Comunidade</span><h2 id="community-detail-title">${deps.escapeHtml(community.name)}</h2><p class="compendium-entry-detail-summary">${deps.escapeHtml(community.summary)}</p><section class="compendium-entry-detail-section"><h3>Feature de comunidade</h3><div class="compendium-entry-feature-grid"><article class="compendium-entry-feature"><h4>${deps.escapeHtml(feature?.name ?? "Feature indisponível")}</h4><p>${deps.escapeHtml(feature?.summary ?? "")}</p></article></div></section><section class="compendium-entry-detail-section"><h3>Referências narrativas</h3><div class="trait-list">${community.adjectives.map((adjective) => `<span>${deps.escapeHtml(adjective)}</span>`).join("")}</div></section></div></section></div>`;
}

export function filterCommunities(communities: CommunityDefinition[], query: string, packId: string): CommunityDefinition[] {
  const normalizedQuery = query.trim().toLocaleLowerCase("pt-BR");
  return communities.filter((community) => (packId === "todos" || community.packId === packId) && (!normalizedQuery || `${community.name} ${community.summary} ${community.adjectives.join(" ")}`.toLocaleLowerCase("pt-BR").includes(normalizedQuery)));
}

export function renderCompendiumCommunityFormModal(deps: CommunityFeatureDependencies): string {
  if (!deps.state.communityModalOpen) return "";
  const community = deps.catalog.communities.find((entry) => entry.id === deps.state.editingCompendiumCommunityId), feature = community ? deps.catalog.features.find((entry) => entry.id === community.featureId) : undefined;
  return `<div class="modal-backdrop" data-modal-backdrop><form class="modal ancestry-form-modal" onsubmit="return false;"><button class="modal-close" type="button" data-action="cancel-compendium-community">×</button><div class="modal-title"><span>Compendium</span><h2>${community ? "Editar comunidade" : "Nova comunidade"}</h2><p>Uma comunidade concede uma Feature e apresenta seis referências narrativas.</p></div><label class="form-field"><span>Nome</span><input data-community-name required value="${deps.escapeHtml(community?.name ?? "")}" /></label><label class="form-field"><span>Descrição</span><textarea data-community-summary required>${deps.escapeHtml(community?.summary ?? "")}</textarea></label><label class="form-field"><span>Adjetivos</span><input data-community-adjectives required value="${deps.escapeHtml(community?.adjectives.join(", ") ?? "")}" placeholder="Ex.: curioso, prático, leal, ..." /><small>Informe exatamente seis, separados por vírgula.</small></label>${renderFeatureAuthoringFields({ key: "community", title: "Feature de comunidade", feature, required: true, escapeHtml: deps.escapeHtml })}<p class="form-error" data-community-error hidden></p><div class="modal-actions"><button class="sf-action sf-action--secondary secondary-action" type="button" data-action="cancel-compendium-community">Cancelar</button><button class="sf-action sf-action--primary primary-action" type="button" data-action="save-compendium-community">Salvar comunidade</button></div></form></div>`;
}

export function renderDeleteCompendiumCommunityModal(deps: CommunityFeatureDependencies): string { const community = deps.catalog.communities.find((entry) => entry.id === deps.state.deletingCompendiumCommunityId); return community ? `<div class="modal-backdrop" data-modal-backdrop><section class="modal confirm-modal"><h2>Excluir comunidade?</h2><p>"${deps.escapeHtml(community.name)}" e sua Feature serão removidas deste dispositivo.</p><div class="modal-actions"><button class="sf-action sf-action--secondary secondary-action" type="button" data-action="cancel-delete-compendium-community">Cancelar</button><button class="sf-action sf-action--danger danger-action" type="button" data-action="confirm-delete-compendium-community">Excluir</button></div></section></div>` : ""; }

export function handleCommunityAction(target: HTMLElement, deps: CommunityFeatureDependencies): boolean {
  const preview = target.closest<HTMLElement>("[data-community-preview-id]"); if (preview) { deps.state.compendiumCommunityPreviewId = preview.dataset.communityPreviewId; deps.render(); return true; }
  if (target.closest('[data-action="new-compendium-community"]')) { deps.state.communityModalOpen = true; deps.state.editingCompendiumCommunityId = undefined; deps.render(); return true; }
  const edit = target.closest<HTMLElement>('[data-action="edit-compendium-community"]'); if (edit) { deps.state.communityModalOpen = true; deps.state.editingCompendiumCommunityId = edit.dataset.communityId; deps.render(); return true; }
  if (target.closest('[data-action="cancel-compendium-community"]')) { deps.state.communityModalOpen = false; deps.state.editingCompendiumCommunityId = undefined; deps.render(); return true; }
  if (target.closest('[data-action="save-compendium-community"]')) { void saveCommunity(deps); return true; }
  const remove = target.closest<HTMLElement>('[data-action="delete-compendium-community"]'); if (remove) { deps.state.deletingCompendiumCommunityId = remove.dataset.communityId; deps.render(); return true; }
  if (target.closest('[data-action="cancel-delete-compendium-community"]')) { deps.state.deletingCompendiumCommunityId = undefined; deps.render(); return true; }
  if (target.closest('[data-action="confirm-delete-compendium-community"]')) { void removeCommunity(deps); return true; }
  return false;
}

export function renderCompendiumFourthSpread(renderChapterCard: (chapter: ChapterCard) => string): string { return `<section class="compendium-spread compendium-index-spread" aria-label="Condições e transformações do Compendium"><article class="compendium-page">${renderChapterCard({ eyebrow: "Em preparação", title: "Condições", summary: "Efeitos temporários e oficiais que serão introduzidos com conteúdo e fluxo de jogo suficientes.", count: 0, countLabel: "Condições cadastradas", primaryAction: "Implementação futura", secondaryAction: "Sem capítulo disponível", details: ["Condições são reconhecidas pelo modelo de domínio.", "O SoulForge ainda não oferece cadastro ou uso delas na ficha."] })}</article><article class="compendium-page">${renderChapterCard({ eyebrow: "Em preparação", title: "Transformações", summary: "Opções narrativas e mecânicas futuras, incluindo conteúdo de expansões quando houver Pack adequado.", count: 0, countLabel: "Transformações cadastradas", primaryAction: "Implementação futura", secondaryAction: "Sem capítulo disponível", details: ["Não há regras ou conteúdo instalado nesta etapa.", "O capítulo será aberto apenas com modelo declarativo e Pack próprio."] })}</article></section>`; }

function renderCommunityResult(community: CommunityDefinition, deps: CommunityFeatureDependencies): string { const feature = deps.catalog.features.find((entry) => entry.id === community.featureId), local = community.packId === "local"; return `<article class="compendium-class-result compendium-ancestry-result"><button class="compendium-class-result-open compendium-ancestry-result-open" type="button" data-community-preview-id="${deps.escapeHtml(community.id)}" aria-label="Ver detalhes de ${deps.escapeHtml(community.name)}"><span class="compendium-class-image class-image-placeholder" aria-hidden="true"></span><span class="compendium-class-body"><span>${deps.escapeHtml(local ? "Local" : deps.getPackDisplayName(community.packId))}</span><h2>${deps.escapeHtml(community.name)}</h2><p>${deps.escapeHtml(community.summary)}</p><span class="ancestry-feature-pair"><span><b>Feature de comunidade</b><strong>${deps.escapeHtml(feature?.name ?? "Feature indisponível")}</strong><small>${deps.escapeHtml(feature?.summary ?? "")}</small></span><span><b>Referências narrativas</b><small>${community.adjectives.map(deps.escapeHtml).join(" · ")}</small></span></span></span></button><div class="compendium-card-result-actions">${local ? `<button class="sf-action sf-action--secondary sf-action--compact" type="button" data-action="edit-compendium-community" data-community-id="${deps.escapeHtml(community.id)}">Editar</button><button class="sf-action sf-action--danger sf-action--compact" type="button" data-action="delete-compendium-community" data-community-id="${deps.escapeHtml(community.id)}">Excluir</button>` : '<span class="readonly-label">Conteúdo não editável</span>'}</div></article>`; }
async function saveCommunity(deps: CommunityFeatureDependencies): Promise<void> { const value=(selector:string)=>document.querySelector<HTMLInputElement|HTMLTextAreaElement>(selector)?.value.trim()??"",name=value("[data-community-name]"),summary=value("[data-community-summary]"),adjectives=value("[data-community-adjectives]").split(",").map((item)=>item.trim()).filter(Boolean),error=document.querySelector<HTMLElement>("[data-community-error]"),existing=deps.catalog.communities.find((entry)=>entry.id===deps.state.editingCompendiumCommunityId),existingFeature=existing?deps.catalog.features.find((entry)=>entry.id===existing.featureId):undefined,feature=readFeatureAuthoringFields({key:"community",feature:existingFeature,sourceType:"community",tier:"community"}); if(!name||!summary||!feature||feature instanceof Error||adjectives.length!==6){if(error){error.hidden=false;error.textContent=feature instanceof Error?feature.message:"Preencha todos os campos e informe exatamente seis adjetivos.";}return;} const id=existing?.id??`community.local.${crypto.randomUUID()}`,featureId=existing?.featureId??feature.id; await Promise.all([deps.saveCustomDefinition({id,type:"community",packId:"local",name,summary,adjectives,featureId}),deps.saveCustomDefinition({...feature,id:featureId,sourceId:id})]); await deps.refreshCatalog(); deps.state.communityModalOpen=false; deps.state.editingCompendiumCommunityId=undefined; deps.render(); }
async function removeCommunity(deps: CommunityFeatureDependencies): Promise<void> { const community=deps.catalog.communities.find((entry)=>entry.id===deps.state.deletingCompendiumCommunityId); if(!community||community.packId!=="local")return; await Promise.all([community.id,community.featureId].map(deps.deleteCustomDefinition)); await deps.refreshCatalog(); deps.state.deletingCompendiumCommunityId=undefined; deps.render(); }
