import type { GameMarkerDefinition } from "../../domain/types";

/** Campos declarativos reutilizados por qualquer fonte que conceda um marcador. */
export function renderGameMarkerFields(key: string, marker: GameMarkerDefinition | undefined, escapeHtml: (value: string) => string): string {
  const counter = marker?.kind === "counter" ? marker : undefined;
  const dice = marker?.kind === "dice" ? marker : undefined;
  const quantity = dice?.quantity;
  return `<fieldset class="game-marker-form"><legend>Marcador de jogo <small>Opcional; aparece na ficha quando esta fonte estiver ativa.</small></legend><div class="form-grid"><label class="form-field"><span>Rotulo</span><input data-game-marker-label="${key}" value="${escapeHtml(marker?.label ?? "")}" placeholder="Ex.: Cargas arcanas" /></label><label class="form-field"><span>Tipo</span><select data-game-marker-kind="${key}"><option value="counter" ${!dice ? "selected" : ""}>Contador</option><option value="dice" ${dice ? "selected" : ""}>Dados</option></select></label><label class="form-field"><span>Valor inicial</span><input data-game-marker-initial="${key}" type="number" min="0" step="1" value="${counter?.initialValue ?? 0}" /></label><label class="form-field"><span>Valor maximo</span><input data-game-marker-max="${key}" type="number" min="0" step="1" value="${counter?.max ?? ""}" placeholder="Sem limite" /></label><label class="form-field"><span>Reinicia em</span><select data-game-marker-reset="${key}"><option value="">Nao reinicia</option>${(["session", "short-rest", "long-rest"] as const).map((reset) => `<option value="${reset}" ${marker?.reset === reset ? "selected" : ""}>${reset === "session" ? "Sessao" : reset === "short-rest" ? "Descanso breve" : "Descanso longo"}</option>`).join("")}</select></label><label class="form-field"><span>Dado</span><select data-game-marker-die="${key}"><option value="d4" ${dice?.die !== "d6" ? "selected" : ""}>d4</option><option value="d6" ${dice?.die === "d6" ? "selected" : ""}>d6</option></select></label><label class="form-field"><span>Quantidade de dados</span><select data-game-marker-quantity-kind="${key}"><option value="fixed" ${quantity?.kind === "fixed" || !quantity ? "selected" : ""}>Quantidade fixa</option><option value="attribute" ${quantity?.kind === "attribute" ? "selected" : ""}>Atributo</option><option value="spellcast-trait" ${quantity?.kind === "spellcast-trait" ? "selected" : ""}>Atributo de Conjuracao</option></select></label><label class="form-field"><span>Quantidade / atributo</span><input data-game-marker-quantity-value="${key}" value="${quantity?.kind === "fixed" ? quantity.value : quantity?.kind === "attribute" ? quantity.attributeId : "1"}" placeholder="Ex.: 2 ou for" /></label></div></fieldset>`;
}

export function readGameMarker(key: string, existingMarkerId?: string): GameMarkerDefinition | undefined | Error {
  const value = (name: string) => document.querySelector<HTMLInputElement | HTMLSelectElement>(`[data-game-marker-${name}="${key}"]`)?.value.trim() ?? "";
  const label = value("label"); if (!label) return undefined;
  const kind = value("kind"); const reset = value("reset") || undefined; const id = existingMarkerId ?? `marker.local.${crypto.randomUUID()}`;
  if (kind === "counter") { const initialValue = Number(value("initial")); const rawMax = value("max"); const max = rawMax ? Number(rawMax) : undefined; if (!Number.isInteger(initialValue) || initialValue < 0 || (max !== undefined && (!Number.isInteger(max) || max < initialValue))) return new Error("Informe valores validos para o contador."); return { id, kind: "counter", label, initialValue, ...(max === undefined ? {} : { max }), ...(reset ? { reset: reset as "session" | "short-rest" | "long-rest" } : {}) }; }
  const die = value("die") as "d4" | "d6"; const quantityKind = value("quantity-kind"); const rawQuantity = value("quantity-value"); const quantity = quantityKind === "fixed" ? { kind: "fixed" as const, value: Number(rawQuantity) } : quantityKind === "attribute" ? { kind: "attribute" as const, attributeId: rawQuantity as "for" | "dex" | "con" | "int" | "wil" | "cha" } : { kind: "spellcast-trait" as const };
  if ((quantity.kind === "fixed" && (!Number.isInteger(quantity.value) || quantity.value < 1)) || (quantity.kind === "attribute" && !["for", "dex", "con", "int", "wil", "cha"].includes(quantity.attributeId))) return new Error("Informe uma quantidade ou atributo valido para os dados.");
  return { id, kind: "dice", label, die, quantity, reset: "session" };
}
